{
  imports = [
    ./alacritty.nix
    ./browsers.nix
    ./calendar
    ./communication.nix
    ./devtools.nix
    ./email
    ./git.nix
    ./gpg.nix
    ./multimedia.nix
    ./neovim
    ./newsboat.nix
    ./scripts
    ./ssh.nix
    ./symlinks.nix
    ./syncthing.nix
    ./tmux.nix
    ./tracktime.nix
    ./udiskie.nix
    ./window-manager
    ./xdg.nix
    ./zsh
  ];
}
