exclude: "secrets/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/nix-community/nixpkgs-fmt/
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt
