exclude: "secrets/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown, vim]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
